backend:
  name: test-repo

media_folder: static/assets
public_folder: /assets
site_url: https://janw.netlify.app
display_url: https://janw.netlify.app

collections:
  - name: projects
    label: Projects
    label_singular: Project
    description: This collection includes all projects shown in the project section.
    folder: projects
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: imagePath, label: Image Path }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }