backend:
  name: github
  repo: jan2210/portfolio-website
  branch: master

media_folder: static/assets
public_folder: /assets
site_url: https://janw.netlify.app
display_url: https://janw.netlify.app

collections:
  - name: projects
    label: Projects
    label_singular: Project
    description: This collection includes all projects shown in the project section.
    folder: projects
    format: json
    extension: json
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image, allow_multiple: false, default: "/uploads/chocolate-dogecoin.jpg", choose_url: false }
      - { name: title, label: Title }
      - { name: downloadUrl, label: Download Url }
      - { name: downloadUrlText, label: Download Url Text }
      - { name: informationUrl, label: Information Url }
      - { name: informationUrlText, label: Information Url Text }
      - { name: appstoreUrl, label: App StoreUrl Url }
      - { name: playstoreUrl, label: Play StoreUrl Url }
      - { name: repoName, label: GitHub Repository Name }
      - { name: description, label: Description, widget: markdown }