backend:
  name: github
  repo: jan2210/portfolio-website
  branch: master

media_folder: static/assets
public_folder: /assets
site_url: https://janw.netlify.app
display_url: https://janw.netlify.app

collections:
  - name: projects
    label: Projects
    label_singular: Project
    description: This collection includes all projects shown in the project section.
    folder: static/projects
    format: json
    extension: json
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }


      - label: "Image"
        name: "imageSection"
        widget: "object"
        collapsed: true
        fields: 
          - { name: image, label: Image, widget: image, allow_multiple: false, choose_url: false }
          - { name: 'color', label: 'Color',  widget: 'color' }
          - { name: 'isFullscreen', label: 'Is Fullscreen Image', widget: 'boolean'} 

      - label: "Links"
        name: "linkSection"
        widget: "object"
        collapsed: true
        fields: 
          - { name: repoName, label: GitHub Repository Name }
          - { name: url, label: Url, required: false }
          - { name: urlText, label: Url Text, required: false }
          - { name: appstoreUrl, label: App StoreUrl Url, required: false }
          - { name: playstoreUrl, label: Play StoreUrl Url, required: false }

  - name: github
    label: Github repositories
    label_singular: Github repository
    description: This collection includes all github links shown in the github section.
    folder: static/github
    format: json
    extension: json
    create: true
    fields:
      - { name: title, label: Title (internal) }
      - { name: repoName, label: GitHub Repository Name }
