backend:
  name: github
  repo: jan2210/portfolio-website
  branch: master

media_folder: static/assets
public_folder: /assets
site_url: https://wermeckes.com
display_url: https://wermeckes.com
logo_url: https://wermeckes.com/assets/favicon.png

collections:
  - name: projects
    label: Projects
    label_singular: Project
    description: This collection includes all projects shown in the project section.
    folder: static/projects
    format: json
    extension: json
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
      
      - { name: image, label: Image, widget: image, hint: Aspect ratio 1000/640, allow_multiple: false, choose_url: false }

      - label: "Links"
        name: "linkSection"
        widget: "object"
        collapsed: true
        fields: 
          - { name: url, label: Url }
          - { name: appstoreUrl, label: App StoreUrl Url, required: false }
          - { name: playstoreUrl, label: Play StoreUrl Url, required: false }

  - name: githubRepos
    label: Github repositories
    label_singular: Github repository
    description: This collection includes all github links shown in the github section.
    folder: static/githubRepos
    format: json
    extension: json
    create: true
    fields:
      - { name: title, label: Title (internal) }
      - { name: repoName, label: GitHub Repository Name }
